uploads = []
generated = []

[[outputs]]
id = "GTyOr6MRMblW6tEtNgKFY"
uri = "file://exports/annonces.csv"
type = "table"
title = "Annonces TogoMarket"

[[outputs]]
id = "LJzcCJnJPItR9nrw2MH77"
uri = "file://exports/commandes.csv"
type = "table"
title = "Commandes TogoMarket"

[[outputs]]
id = "AOjQAeJ0CMcyeLnnA6N3C"
uri = "file://togomarket-pro.zip"
type = "unspecified"
title = "TogoMarket Pro — Code source complet"
